@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU of clickItemButton(CU04)

participant "appController:Controller" as ac
participant "buttonList:ButtonList" as bl
participant "button:ItemButton" as b

note left of ac: Controller
->ac : clickItemButton(button)

note left of bl: High Cohesion
ac->bl : buttonRemoved = buttonList.removeButtonOccurence(button)

note left of b: Low Coupling
bl->b: buttonRemoved = button.removeOccurence()

opt buttonRemoved
    note left of bl: Expert
    ac->bl : buttonList.removeButton(button)
end opt

@enduml

@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU of updateButonList(CU04)

participant "appController:Controller" as ac
participant "buttonList:ButtonList" as bl
participant "button:ItemButton" as ib

note left of bl: Expert
ac->bl : buttonList.updateButtons()

loop for each ItemButton  of the ButtonList
note left of ib: Expert
bl->ib : button.updateProb(buttonList.nbItems) 
end loop


@enduml