@startuml
left to right direction
skinparam style strictuml
skinparam packageStyle rect
skinparam backgroundcolor transparent
skinparam defaultfontname Verdana

title DCU - Randomizer Tracker Project

actor Player as P

rectangle "System" {
  (Load an Item List) as LL
  (Save an Item List) as SL
  (Categorize an Item of the List) as CI
  (Recategorize an Item of the List) as RCI
  (Remove an Item of the List) as RI
  (Undo an Item Removal) as UIR
  (Reset the ButtonList) as RBL
  (Undo Reset the List) as UR
  (Submit Leftover Report) as SR
  (Open Stats Page) as OS
  
  P -- LL
  P -- SL
  P -- CI
  P -- RI
  P -- UIR
  P -- RBL
  P -- UR
  P -- OS
  P -- SR
}
@enduml