@startuml 
skinparam style strictuml
skinparam DefaultFontName Verdana
skinparam backgroundcolor transparent
skinparam sequenceMessageAlign center
title DSS - Load an ItemList

actor ":User" as u
participant ":Application" as a 

u -> a : clickItemButton(Button)
a --> u : Reduced the occurence of button by 1

u -> a : updateButtonList()
a --> u : ButtonList Updated

@enduml
