@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam ControlStereotypeFontColor #blue
left to right direction
hide empty members
'skinparam linetype ortho

title MDD

class User <C05> {}

class Menu <C13> {
    tabs:  tabs
    buttons: button
}

class ItemList <C11> {
    items : ArrayList<Object> 
}
class Item <C12>  {
  name : string
  occurences : integer
}

class ButtonList<C11>{
    buttons: ArrayList<Button>
}

class Button <C08 & C12> {}

class ListExtractor <C13> {}

class Document <C14> {
    link : string
}

Document "1" -- "1" Menu : Selected in\nA08
ListExtractor "1" -- "1" Document : > Uses\nA11

User "1" -- "1" Menu : > Uses\nA11
ButtonList "1" -l- "1" User :  Uses\nA11

ListExtractor "1" -- "1" ButtonList :  Creates\nA11
ListExtractor "1" -- "1" ItemList : Creates\nA11

ItemList "1" -l- "1" ButtonList : Represents\nA07
ButtonList "1" -- "*" Button : Manages\nA11

Item "*" -- "1" ItemList : > are saved in\nA08

@enduml